name: Build Typst document
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: 'MIPS Reference Sheet.typ'

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: 'MIPS Reference Sheet'
          path: '*.pdf'